# 验证码配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
spring:
  thymeleaf:
    cache: false
redisCache:
  expire: 50400
  keyPrefix: sso_cache
redisSession:
  expire: 50400
  keyPrefix: sso_session
oauth2:
  expire:
    code: 180
    token: 21600
    refreshToken: 604800
  login:
    mutex: false
  user:
    autoCreate: false
  token:
    sm4key: 143be1ae6ee10b048f7e441cec2a9803
wechat:
  miniapp:
    appId: wx*************4a3
    secret: a6***************efa227