gateway:
  routes:
    - path: /oauth2
      packageName: cn.com.axel.oauth
    - path: /scheduler
      packageName: cn.com.axel.scheduler
    - path: /storage
      packageName: cn.com.axel.storage
    - path: /sys
      packageName: cn.com.axel.sys
    - path: /demo
      packageName: cn.com.axel.demo
    - path: /nocode
      packageName: cn.com.axel.nocode